# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержимое заметки')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unique_words', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['unique_words'],
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
